# @package _global_
# Main configuration file for Bench-MFG experiments

defaults:
  - _self_
  - algorithm: pso
  - environment: kinetic_congestion
  - experiment: experiment
  - logging: logging
  - visualization: visualization

device: "cpu" # "cpu", "cuda:0", "cuda:1", etc.

initialization:
  initialization_type: "PSO_uniform"
  init_policy_temp: 0.2

hydra:
  run:
    dir: .hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: .hydra_logs/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${hydra.job.num}
  job:
    name: mfg_experiment
